### ISSUE TITLE
O-Cows not breeding/no babies born

### ISSUE THREAD

**Issue by Lovegameselfie** [DragN0007/Overhauled-Livestock#16]
**Bug Description:**
When breeding two cows a male(no udders) and female(udders), the hearts appear however no baby cow spawns no matter how many times tried. The love particles show up but no baby is born. I tested if no baby’s could be born at all by breeding two horses together however a baby horse did appear after breeding the two. I tried breeding the cows again and no baby spawned, I even made sure to double check it was a male and female I was breeding and it was so I’m unsure if it’s only the cows that just aren’t breeding properly. I haven’t tested if any of the other animals can’t breed so I’m unsure if this is just an issue with the cow programming/script or if other O-Animals aren’t breeding properly except for the horses.

**Mod Version:**
1.20.1
**Minecraft Version:**
1.20.1
**Screenshot (Optional):**

**Have you tried removing other mods? Did the issue persist after removing them?:**
Yes I tried removing both mods and resource packs as well as re-downloading the mod but still didn’t have any baby cows spawn.
**Are you on Singleplayer or a Server?:**
Single player.

**Comment by DragN0007** [comment]
Make sure you're on versions 1.4+. This issue was fixed in 1.4+ versions. If your cows are from earlier versions, kill/ release them and find new ones in new chunks that have been spawned after the 1.4 update.

If you're in 1.4+, and you've smacked one of your cows recently, either go to bed and sleep through the night or reload your game and try again
